### PR TITLE
refactor: manage route in extension

### PR DESCRIPTION
**Pull request by conwnet**
Before that PR, we use this file to manage the current repository ref(branch/tag/commit), and the logic here is rather chaotic:
https://github.com/conwnet/github1s/blob/63e377a/extensions/github1s/src/helpers/git-ref.ts

Now I rearrange the relevant logic in the PR:

- Move the route logic here:
https://github.com/conwnet/github1s/tree/48e779d/extensions/github1s/src/router

- Store the repository state here:
https://github.com/conwnet/github1s/blob/48e779d49300235bfb7037b2cde320200e771604/extensions/github1s/src/repository.ts

- Move the initial opened editor logic (open corresponding editor if there is a filePath specified in browser url) from `vscode` into `github1s extension`:
https://github.com/conwnet/github1s/blob/48e779d493/extensions/github1s/src/extension.ts#L108

**Why:**

- Use the routerState as the single state source. The router change will trigger a series of listeners:
https://github.com/conwnet/github1s/tree/48e779d49300235bfb7037b2cde320200e771604/extensions/github1s/src/listeners/router
We will support PR/commit for better Code Review experience next. For example, when we switch to a PR View, it will trigger the `File Explorer` change, the `Source Control` Changes, the `Status Bar Branch Indicator` change .etc. Or switch to a Commit View, It also will trigger a series other action. It is a challenge to manage the state of every part. So I think we need a `Single State Source` which all listeners listened it, once the `Single State Source` changed, all listenters should be notified.

- Reduce the modification of the original VSCode source code as much as possible.
Before that, we process the initial opened file in https://github.com/conwnet/github1s/blob/48e779d493/src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts , now I moved it to the `github1s extension`. Now the `welcomePage.ts` only includes the `Custom Welcome Page` logic.

The code modification is quite big in this PR, please help me to review it, thanks @xcv58 @Siddhant-K-code @mikenikles  🥰
Of course, I'll do more tests myself too.

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
` build (15.x, macos-latest)` failed !!

**Comment by conwnet** [comment]
> ` build (15.x, macos-latest)` failed !!

Yes, It's still the cause by the Rate Limit. GitHub1s will open the welcome page if the rate limit is exceeded, which is break the integration test

**Review by Siddhant-K-code — APPROVED** [review]
LGTM!

**Review by xcv58 — APPROVED** [review]
Reviewed the code and tested it via Vercel. It works well.

Thank you @conwnet!

**Pull request merged**
