### PR TITLE
📝 Update README.md with Tampermonkey scripts

### PR DESCRIPTION
**Pull request by Mr-B0b**
Hi,

Cool project 👍 

I added a link to the project README with a tampermonkey script I developped.

The script adds a `Open with VSCode` button to Github repositories pages:

image

Thanks ;)

Regards,

### CODE REVIEW

**Comment by lonelykid** [comment]
Not even worth to use a userscript. A bookmarklet will do. Maybe you could just add one more commit to your PR.

**Review by Siddhant-K-code — APPROVED** [review]
I think we already have a chrome extension for this !!

**Review by Siddhant-K-code — COMMENTED** [review]
I think we already have a chrome extension for this!!

**Comment by Mr-B0b** [comment]
Hi,

Thanks for your comments.

This script is just a simple alternative for users who are already using Tampermonkey and don't want to add any additional extensions.

I think this could be a good addition for the community.

Regards,

**Comment by xcv58** [comment]
I think it's a necessary supplement for those who don't like to install extensions.

**Review by Siddhant-K-code — APPROVED** [review]

**Pull request merged**
