### PR TITLE
feat: add prettier and auto format files during git commit

### PR DESCRIPTION
**Pull request by xcv58**
The change after `yarn format` will look like this: https://github.com/xcv58/github1s/pull/8/files

### CODE REVIEW

**Comment by xcv58** [comment]
It seems we have to merge https://github.com/xcv58/github1s/pull/8 first to avoid the `eslint` issue on CI.

**Comment by Siddhant-K-code** [comment]
Yes, because there are too many errors while checks, it can lead to build fail, ig

**Comment by xcv58** [comment]
> Yes, because there are too many errors while checks, it can lead to build fail, ig

I merged the https://github.com/xcv58/github1s/pull/8

It should pass the action check more. Please feel free to raise if you have any concerns since it’s large change 
 cc @conwnet for visibility.

**Review by Siddhant-K-code — APPROVED** [review]
All Good, Checks Passed ✅

**Comment by Siddhant-K-code** [comment]
I think we are ready to merge this, @xcv58  @conwnet

**Comment by conwnet** [comment]
lgtm, thanks!

**Pull request merged**
