### PR TITLE
Added greeting bot🤖

### PR DESCRIPTION
**Pull request by himanshu007-creator**
This bot will be really helpful to motivate newbies. Contributors will be greeted with a message whenever they:-
1. Create their first pull request
2. Create their first issue
3. get first PR merged.

related to issue #195

### CODE REVIEW

**Review by Siddhant-K-code — APPROVED** [review]
LGTM!

**Review by Siddhant-K-code — CHANGES_REQUESTED** [review]
It Would Be Good if there will be `github1s` instead of GITHUB1S at Line 21 !!

**Comment by himanshu007-creator** [comment]
> It Would Be Good if there will be `github1s` instead of GITHUB1S at Line 21 !!

Made the changes👍🏽

**Review by conwnet — APPROVED** [review]
LGTM, Thanks~

**Review by conwnet — APPROVED** [review]

**Review by conwnet — APPROVED** [review]

**Review by Siddhant-K-code — APPROVED** [review]
LGTM! Thanks <3

**Pull request merged**
