### PR TITLE
Feature/compact opera

### LINKED ISSUE #324: Not working in opera browser
image

### PR DESCRIPTION
**Pull request by conwnet**
This PR fixes #324

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
Ubuntu 20 test is failing again?

**Review by Siddhant-K-code — APPROVED** [review]
LGTM! Will Send you the updated report after testing on Opera Browser

**Comment by conwnet** [comment]
> LGTM! Will Send you the updated report after testing on Opera Browser

Thank you! It should works after we publish a new version of `vscode-web` package, I will do it with another feature together

**Comment by Siddhant-K-code** [comment]
> > LGTM! Will Send you the updated report after testing on Opera Browser
> 
> Thank you! It should works after we publish a new version of `vscode-web` package, I will do it with another feature together

I and @shubhanshu-1507 Testing the Vercel Preview deployment, i.e. : https://github1s-git-feature-compact-opera-vscode-github1s.vercel.app/

**Review by Shubhanshu-1507 — COMMENTED** [review]
https://github1s-git-feature-compact-opera-vscode-github1s.vercel.app/ is  still  giving same error 
unknown

https://github1s-60y90g8oe-vscode-github1s.vercel.app/ this link also giving issues still showing some errors Screenshot 2021-06-10 193758

**Comment by conwnet** [comment]
> https://github1s-git-feature-compact-opera-vscode-github1s.vercel.app/ is still giving same error
> unknown
> 
> https://github1s-60y90g8oe-vscode-github1s.vercel.app/ this link also giving issues still showing some errors Screenshot 2021-06-10 193758

Thanks for your testing, yes this is because we only modified the source code but didn't publish a new version of `@github1s/vscode-web` package on npm. I will publish it next~

**Comment by Siddhant-K-code** [comment]
> Thanks for your testing, yes this is because we only modified the source code but didn't publish a new version of `@github1s/vscode-web` package on npm. I will publish it next

Yeah, but these changes should reflect in Vercel Deployment Preview?

**Comment by conwnet** [comment]
> Yeah, but these changes should reflect in Vercel Deployment Preview?

Not yet, our build in Vercel preview also use the prebuilt package in npm.

**Comment by conwnet** [comment]
> > Thanks for your testing, yes this is because we only modified the source code but didn't publish a new version of `@github1s/vscode-web` package on npm. I will publish it next
> 
> Yeah, but these changes should reflect in Vercel Deployment Preview?

Hey, the Vercel preview deployment has updated now, and it works in opera browser during my test~🚀

**Review by Siddhant-K-code — APPROVED** [review]
LGTM 🎉

**Comment by Shubhanshu-1507** [comment]
yeah now https://github1s-o79fimw2g-vscode-github1s.vercel.app/ 
working properly 
3c46ec2b-e457-4239-a2cb-69f1bef52598

**Comment by Siddhant-K-code** [comment]
Thanks @Shubhanshu-1507 for the review.

**Comment by conwnet** [comment]
> Thanks @Shubhanshu-1507 for the review.

@Shubhanshu-1507 Thank you so much! ❤️

**Pull request merged**
