### PR TITLE
feat: support for pull request list

### PR DESCRIPTION
**Pull request by conwnet**
suport for pull request lists

### CODE REVIEW

**Comment by conwnet** [comment]
Code changes:
https://github1s.com/conwnet/github1s/pull/235

**Review by xcv58 — COMMENTED** [review]
Sample URL can be found: https://github1s-git-feature-pulls-vscode-github1s.vercel.app/conwnet/github1s/pulls

image




Since we get the pulls information, should we add typeahead like this?
image

 
image

**Comment by conwnet** [comment]
@xcv58 Thanks for your suggestion, I will fix it today~

**Comment by conwnet** [comment]
> @xcv58 Thanks for your suggestion, I will fix it today~

I have add the search for pull request~ (but only for first 100 pull requests...)

**Review by xcv58 — APPROVED** [review]
This is amazing!

**Review by Siddhant-K-code — COMMENTED** [review]
This is Awesome 🔥

**Pull request merged**
