### PR TITLE
feat: add open changes button to editor title

### PR DESCRIPTION
**Pull request by conwnet**
image

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
@conwnet pls check gitter messages

**Comment by Siddhant-K-code** [comment]
it's doesn't getting pop up : 
image

**Comment by conwnet** [comment]
> it's doesn't getting pop up :
> image

the button would only show on the file title when the files that exists in `source-contorl-panel Changes`

**Review by Siddhant-K-code — APPROVED** [review]
LGTM! Good 🎉

**Pull request merged**
