### PR TITLE
feat: support for the file git blame

### PR DESCRIPTION
**Pull request by conwnet**
Support for viewing the git blame data of a file.
The UI is inspired by [vscode-gitlens](https://github.com/eamodio/vscode-gitlens)

### CODE REVIEW

**Comment by conwnet** [comment]
image

**Comment by justanotheranonymoususer** [comment]
I think that "Ignore" implies "Do it anyway". Perhaps rename it to "Dismiss", or just show one button - there's the x button that closes the message.

image

**Review by Siddhant-K-code — APPROVED** [review]
Great 🎉

**Comment by conwnet** [comment]
> I think that "Ignore" implies "Do it anyway". Perhaps rename it to "Dismiss", or just show one button - there's the x button that closes the message.
> 
> image

Thank you, I have removed the `Ignore` button

**Comment by conwnet** [comment]
> Great 🎉

@Siddhant-K-code Thank you so much! I have changed the code (remove the `Ignore` button), please help me to review again 🙏

**Comment by Siddhant-K-code** [comment]
> > Great 🎉
> 
> @Siddhant-K-code Thank you so much! I have changed the code (remove the `Ignore` button), please help me to review again 🙏

Oh Okay, not many changes are done after review, all are working fine, will verify it once after deployment and tests run.

**Review by Siddhant-K-code — APPROVED** [review]
LGTM! Good Work.

**Pull request merged**
