### PR TITLE
feat: support to install extensions from microsoft marketplace

### PR DESCRIPTION
**Pull request by conwnet**

### CODE REVIEW

**Comment by conwnet** [comment]
But only extensions which support to run on web can be installed

image

**Comment by Siddhant-K-code** [comment]
All things are working fine, but We have to remove extensions like these. 

image

**Review by Siddhant-K-code — DISMISSED** [review]

**Review by xcv58 — APPROVED** [review]

**Comment by xcv58** [comment]
> But only extensions which support to run on web can be installed
> 
> image

I actually found a weird issue.

https://github1s-git-feature-extensions-conwnet.vercel.app

After I install the VIM extension, the `hjkl` key couldn't move the cursor. I suspect it might relate to the read-only mode. @conwnet do you have any clues?

**Comment by conwnet** [comment]
> > But only extensions which support to run on web can be installed
> > 
> > image
> 
> I actually found a weird issue.
> 
> https://github1s-git-feature-extensions-conwnet.vercel.app
> 
> After I install the VIM extension, the `hjkl` key couldn't move the cursor. I suspect it might relate to the read-only mode. @conwnet do you have any clues? 

yes, I found it too. It seems cause by vscode self, I am trying to solve this.

**Comment by xcv58** [comment]
> > > But only extensions which support to run on web can be installed
> > > image
> > 
> > 
> > I actually found a weird issue.
> > https://github1s-git-feature-extensions-conwnet.vercel.app
> > After I install the VIM extension, the `hjkl` key couldn't move the cursor. I suspect it might relate to the read-only mode. @conwnet do you have any clues?
> 
> yes, I found it too. It seems cause by vscode self, I am trying to solve this.

I tested it via a local vim plugin and the behavior is the same.

And the same VIM web extension works on https://vscode-web-test-playground.azurewebsites.net/

**Comment by conwnet** [comment]
> > > > But only extensions which support to run on web can be installed
> > > > image
> > > 
> > > 
> > > I actually found a weird issue.
> > > https://github1s-git-feature-extensions-conwnet.vercel.app
> > > After I install the VIM extension, the `hjkl` key couldn't move the cursor. I suspect it might relate to the read-only mode. @conwnet do you have any clues?
> > 
> > 
> > yes, I found it too. It seems cause by vscode self, I am trying to solve this.
> 
> I tested it via a local vim plugin and the behavior is the same.
> 
> And the same VIM web extension works on https://vscode-web-test-playground.azurewebsites.net/

This bug only occurred in a read-only mode editor.

**Comment by xcv58** [comment]
> This bug only occurred in a read-only mode editor.

What's the drawback if we change the `isReadonly` to true?

https://github.com/conwnet/github1s/blob/master/extensions/github1s/src/github1sfs.ts#L230

**Comment by conwnet** [comment]
> > This bug only occurred in a read-only mode editor.
> 
> What's the drawback if we change the `isReadonly` to true?
> 
> https://github.com/conwnet/github1s/blob/master/extensions/github1s/src/github1sfs.ts#L230

I'm just worried that users will be frustrated if they accidentally modify code that can't be saved

**Comment by xcv58** [comment]
> > What's the drawback if we change the `isReadonly` to true?
> > https://github.com/conwnet/github1s/blob/master/extensions/github1s/src/github1sfs.ts#L230
> 
> I'm just worried that users will be frustrated if they accidentally modify code that can't be saved

Confirmed the readonly mode breaks VIM. You can try it https://github.com/conwnet/github1s/pull/187#issuecomment-786391053 when the Vercel is ready.

**Comment by conwnet** [comment]
> > > What's the drawback if we change the `isReadonly` to true?
> > > https://github.com/conwnet/github1s/blob/master/extensions/github1s/src/github1sfs.ts#L230
> > 
> > 
> > I'm just worried that users will be frustrated if they accidentally modify code that can't be saved
> 
> Confirmed the readonly mode breaks VIM. You can try it [#187 (comment)](https://github.com/conwnet/github1s/pull/187#issuecomment-786391053) when the Vercel is ready.

yes, thanks, this bug is only occured in browser version vscode, I am trying to fixed it

**Comment by conwnet** [comment]
@xcv58 
VIM extensions should worked now: https://github1s-git-feature-extensions-conwnet.vercel.app

VSCode add a `readonly` attribute to editor textarea element, which is used to prevent the default keyboard popping on mobile devices. It break the `vscode.workspace.onDidChangeTextDocument` API which is used by VIM extension. This issue would occured in CodeSpaces too.

I just remove this here. https://github.com/conwnet/github1s/pull/183/files#diff-37a993adfbbcde6d9fd8e61da6637960bcce354b618fb1e3dcf6bf6ded66e435R138

I also create an issue about it:
https://github.com/microsoft/vscode/issues/117755

And do you know if there is another better way to prevent keyboard popping on mobile devices instead of insertting a `readonly` attribute to the domNode?

**Review by xcv58 — APPROVED** [review]
Thank you so much!

**Pull request merged**
