### PR TITLE
Add Stargazers

### PR DESCRIPTION
**Pull request by xcv58**
You can preview the change here: https://github.com/xcv58/github1s/tree/starchart#stargazers-over-time

### CODE REVIEW

**Review by Siddhant-K-code — APPROVED** [review]
LGTM! 🎉

**Comment by Siddhant-K-code** [comment]
can we add this below to the maintainers?

**Review by conwnet — APPROVED** [review]
LGTM, awesome, thanks!

**Review by Siddhant-K-code — APPROVED** [review]
Perfect!

**Pull request merged**
