### PR TITLE
Upgrade VS Code to 1.60.0

### LINKED ISSUE #58: Support scala syntax highlighting
Syntax highlight on scala files does not seem to work.

### LINKED ISSUE #66: Support Golang syntax highlighting

### LINKED ISSUE #139: Support Syntax highlighting for Julia
Hello, think this project is awesome!
I would love to see Syntax highlighting for Julia integrated. One could integrate the Julia extension for VS code https://github.com/julia-vscode/julia-vscode
or integrate the syntax files from https://github.com/julia-vscode/julia-vscode/tree/master/syntaxes
e.g.
https://raw.githubusercontent.com/julia-vscode/julia-vscode/master/syntaxes/julia.json

Cheers

### LINKED ISSUE #185: Support for viewing Jupyter notebooks
Is there be an option to view .ipynb files in a format like that provided by Jupyter extension in VS Code?

### PR DESCRIPTION
**Pull request by conwnet**
Upgrade VS Code to 1.60.0.
We can install more extensions now 🚀

Remove custom some extensions includes dart-web, jupyter-web, kotlin-web, scala-web, sevlte-web, veture-web. (we can install them through extension store or use the vscode builtin version)

----
Comment by @Siddhant-K-code:

Fixes #185 
Fixes #58
Fixes #139 
Fixes #66

Not Working #116
Not Working #303 
Not Working #284
Not Working #45

### CODE REVIEW

**Review by Siddhant-K-code — COMMENTED** [review]
Extensions are Working Fine, But Some Tests are failing 😞

**Comment by Siddhant-K-code** [comment]
image


This is a Viewer/Previewer extension, but not working with this!! 
will still need some extension for #284

**Comment by Siddhant-K-code** [comment]
Related to #327

### It Supports
image

### But, Doesn't Support
image

**Comment by Siddhant-K-code** [comment]
Fixes #185
Fixes #58
Fixes #139
Fixes #66

Not Working #116
Not Working #303
Not Working #284
Not Working #45

**Comment by conwnet** [comment]
> ![image
> This is a Viewer/Previewer extension, but not working with this!!
> will still need some extension for #284
Thank you for your review! 🙏🏻
Only a part of extensions are available now.
Let me fix the failed test suites, it seems unstable. 😁

**Review by Siddhant-K-code — COMMENTED** [review]
Update: Tests are passing now, the issue was regarding Timeout.

It is fixed through [cbe17a1](https://github.com/conwnet/github1s/pull/353/commits/cbe17a1db3fc67f7352a2017e3214d75ac0cd20c) pushed by @conwnet

**Review by Siddhant-K-code — APPROVED** [review]
LGTM 🎉 

We Need to Work On Integrating #116, #303, #284, #45 in future PRs

**Comment by s-ayush2903** [comment]
@Siddhant-K-code Can you please reopen closed issues which, by the introduction of this upgradation, got "active" again, in that case please, so that people might get aware of this and not end up creating new issues.
Also the previous Kotlin syntax highlighting looked really awesome!

Thanks!

**Comment by s-ayush2903** [comment]
God! It started working as I installed the Kotlin extension. Sorry for my stupid comment above, I might have read the PR description first before posting anything. Sorry :sweat:

**Comment by Siddhant-K-code** [comment]
I hope, you got your answers!?

**Comment by s-ayush2903** [comment]
Yesss! Thanks

**Pull request merged**
