### PR TITLE
Safari Extension

### PR DESCRIPTION
**Pull request by code4you2021**
Add Safari Extension

### CODE REVIEW

**Review by xcv58 — APPROVED** [review]

**Review by Siddhant-K-code — APPROVED** [review]
LGTM

**Comment by xcv58** [comment]
Thank you @code4you2021

**Comment by Siddhant-K-code** [comment]
I think you can also add Mac App Store link as [GitHub1s-For-Safari-Extension](https://apps.apple.com/us/app/readcodeonline/id1569026520?mt=12)

**Comment by code4you2021** [comment]
@Siddhant-K-code ok,  I have added the link.

**Review by Siddhant-K-code — APPROVED** [review]
Perfect.

Thanks @code4you2021

**Pull request merged**
