### PR TITLE
ci: add macos for github workflows

### PR DESCRIPTION
**Pull request by Lonor**
I build the project on my mac but it failed. Hope this test could pass which can give users some help for troubleshooting.

### CODE REVIEW

**Review by Siddhant-K-code — CHANGES_REQUESTED** [review]
Replace `--network-timeout 500000` at line 37, `1000000` will be too much I guess.

**Review by conwnet — DISMISSED** [review]
Thanks~

**Review by Siddhant-K-code — DISMISSED** [review]
All Things Are fine now, Good Work ❤️

**Review by xcv58 — APPROVED** [review]

**Comment by Lonor** [comment]
Hey, I just figured out the reason how the CI failed on the previous occasions: The GitHub API has the rate limit (when downloading the dependencies of the `vscode-ripgrep`). All the procedures are in my own pull request (https://github.com/Lonor/github1s/pull/1#issuecomment-796393712).

> If the upstream repo's Action still get the 403 response when GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v12.1.1-4, I'll considering add the GITHUB_TOKEN to the Actions environment to improve the success rate of `yarn`.

So I try to improve the success rate of this CI by adding the `GITHUB_TOKEN` to the environment variables and it works. I'll append it right now.

**Comment by Lonor** [comment]
It failed with the `gyp` on Ubuntu. @conwnet Could you please re-trigger this Action? It's success in my repo. Very weird.

**Comment by xcv58** [comment]
> It failed with the `gyp` on Ubuntu. @conwnet Could you please re-trigger this Action? It's success in my repo. Very weird.

Can you try to fire another PR? I think this PR has an issue with the `build (14.x)`.

**Comment by Siddhant-K-code** [comment]
@Lonor it was working fine, why create another changes xD

**Comment by Lonor** [comment]
> > It failed with the `gyp` on Ubuntu. @conwnet Could you please re-trigger this Action? It's success in my repo. Very weird.
> 
> Can you try to fire another PR? I think this PR has an issue with the `build (14.x)`.

Sure. I'll close this.

**Pull request closed without merging**
