### PR TITLE
fix: home logo with light theme

### PR DESCRIPTION
**Pull request by wolfsilver**
The current logo does not perform well on some light themes.

PS: **vscode needs rebuild**.

image

### CODE REVIEW

**Review by Siddhant-K-code — CHANGES_REQUESTED** [review]
SVGs are looking weirdly enlarged. can you pls reduce the size a little bit?

image

**Review by Siddhant-K-code — CHANGES_REQUESTED** [review]
In [Review](https://github1s-git-fork-wolfsilver-fix-home-logo-vscode-github1s.vercel.app/), in dark mode. Logo is not visible.

image

**Comment by wolfsilver** [comment]
> SVGs are looking weirdly enlarged. can you pls reduce the size a little bit?

svg is a vector image, I'll keep it same size with `github.svg`.

**Comment by wolfsilver** [comment]
> In [Review](https://github1s-git-fork-wolfsilver-fix-home-logo-vscode-github1s.vercel.app/), in dark mode. Logo is not visible.
> 
> image

Doesn't `Review` mode rebuild vscode?

**Comment by conwnet** [comment]
> Doesn't Review mode rebuild vscode?
review mode wouldn't rebuild vscode due to speed now.
Thanks your for you contribution. let me rebuild it and make it work.

**Comment by conwnet** [comment]
Thank you for your work!
I think we can use the [css mask](https://developer.mozilla.org/en-US/docs/Web/CSS/mask) attribute instead of `background` to solve this problem.
I prefer to keep a concise API, which is more convenient for users.

**Comment by wolfsilver** [comment]
> Thank you for your work! I think we can use the [css mask](https://developer.mozilla.org/en-US/docs/Web/CSS/mask) attribute instead of `background` to solve this problem. I prefer to keep a concise API, which is more convenient for users.

Sorry，I didn't get it. Different themes set different colors on the parent node. I don't know which css mask attribute can solve this problem.

**Comment by conwnet** [comment]
> Sorry，I didn't get it. Different themes set different colors on the parent node. I don't know which css mask attribute can solve this problem.

I have opened a PR here:
https://github.com/wolfsilver/github1s/pull/1/files

**Review by conwnet — APPROVED** [review]

**Pull request merged**
